### ISSUE TITLE
Weird collision of objects against Triggers / Invisible Ents

### ISSUE THREAD

**Issue by Matsilagi** [Joshua-Ashton/VPhysics-Jolt#62] opened 2022-09-01 16:50 UTC
A few map entities made from brushes / map props seems to have some problems with either entities or invisible brushes in them. I don't know how to explain exactly.

To mimic / see what i mean, i have a video here, but an easy way is getting coop_zelda from Obsidian Conflict, killing the manhacks to reveal the first key, then getting the key across the doors, you'll notice that it will slowly transition to the other side, as if something was giving it resistance.

Video: https://www.youtube.com/watch?v=sXLFWCf7CCI

**Comment by Joshua-Ashton** [comment] 2022-09-01 18:04
Duplicate of https://github.com/Joshua-Ashton/VPhysics-Jolt/issues/1

**Closed by Joshua-Ashton** 2022-09-01 18:04 UTC
