### ISSUE TITLE
Compatibility with 2013 SP branch?

### ISSUE THREAD

**Issue by davie504** [Joshua-Ashton/VPhysics-Jolt#19] opened 2022-08-29 07:09 UTC
![image](https://user-images.githubusercontent.com/59658354/187143862-bf4d15ca-fd23-45b9-a0c9-7ae190ce5610.png)

**Comment by Joshua-Ashton** [comment] 2022-08-29 07:10
Duplicate of: https://github.com/Joshua-Ashton/VPhysics-Jolt/issues/12

**Closed by Joshua-Ashton** 2022-08-29 07:10 UTC
Labels: duplicate

**Comment by Joshua-Ashton** [comment] 2022-09-02 10:07
SDK 2013 SP builds are on the CI now.
