### ISSUE TITLE
Server crash on map clean up

### ISSUE THREAD

**Issue by Marshall-vak** [Joshua-Ashton/VPhysics-Jolt#29] opened 2022-08-29 21:34 UTC
When a map cleanup is called from `game.CleanUpMap()` the server states the following error `free(): corrupted unsorted chunks` and hangs. 

The server is srcds x64 on Linux. Distro: ubuntu

**Comment by Joshua-Ashton** [comment] 2022-08-29 21:55
Duplicate of: https://github.com/Joshua-Ashton/VPhysics-Jolt/issues/17

**Closed by Joshua-Ashton** 2022-08-29 21:55 UTC
Labels: duplicate
